(() => {
 const key='lotusbio-quote-v1';let items=[];
 try{const value=JSON.parse(localStorage.getItem(key)||'[]');if(Array.isArray(value))items=value.filter(x=>typeof x.name==='string'&&typeof x.spec==='string'&&Number.isInteger(x.qty)&&x.qty>0&&x.qty<=100000);}catch{}
 const dialog=document.querySelector('#quote-review');
 function message(){return 'Hello LotusBio, please quote:\n'+items.map(x=>`${x.name} — ${x.spec} — ${x.qty} box(es)`).join('\n')+'\n\nPlease confirm availability, batch documents, packaging and shipping.';}
 function update(){document.querySelectorAll('[data-count]').forEach(x=>x.textContent=items.length);const host=document.querySelector('#quote-items');host.replaceChildren();if(!items.length)host.textContent='Your list is empty. Add a product to request a quote.';items.forEach((item,i)=>{const row=document.createElement('div');row.className='quote-row';const text=document.createElement('p');text.textContent=`${item.name} · ${item.spec} · ${item.qty} box(es)`;const remove=document.createElement('button');remove.type='button';remove.textContent='Remove';remove.setAttribute('aria-label','Remove '+item.name);remove.onclick=()=>{items.splice(i,1);save();};row.append(text,remove);host.append(row);});const body=message();document.querySelector('#quote-email').href='mailto:info@lotusbio.cn?subject=LotusBio%20wholesale%20inquiry&body='+encodeURIComponent(body);document.querySelector('#quote-whatsapp').href='https://wa.me/85292734987?text='+encodeURIComponent(body);}
 function save(){try{localStorage.setItem(key,JSON.stringify(items));}catch{document.querySelector('#quote-storage').textContent='Your browser cannot save this list. Keep this page open until you send your inquiry.';}update();}
 document.querySelector('#add-quote')?.addEventListener('click',()=>{const input=document.querySelector('#quote-qty');if(!input.reportValidity())return;const name=document.querySelector('[data-product]').dataset.product,spec=document.querySelector('#quote-spec').value,qty=Number(input.value);const existing=items.find(x=>x.name===name&&x.spec===spec);if(existing){if(existing.qty+qty>100000){document.querySelector('#quote-status').textContent='Please keep quantity at or below 100000 boxes.';return;}existing.qty+=qty;}else items.push({name,spec,qty});save();document.querySelector('#quote-status').textContent='Added. Open Review quote to check your inquiry.';});
 document.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>dialog.showModal());document.querySelector('#quote-close').onclick=()=>dialog.close();
 document.querySelector('#quote-email').addEventListener('click',()=>{setTimeout(()=>{const status=document.querySelector('#quote-storage');if(status)status.textContent='If your email app did not open, email info@lotusbio.cn manually.';},300);});update();
 const send=document.createElement('button');send.type='button';send.className='button dark';send.textContent='Send inquiry directly';send.onclick=async()=>{const status=document.querySelector('#quote-storage');status.textContent='Sending your inquiry…';try{const response=await fetch('https://formsubmit.co/ajax/info@lotusbio.cn',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({subject:'LotusBio wholesale inquiry',inquiry:message(),_captcha:'false'})});if(!response.ok)throw Error('send failed');status.textContent='Inquiry sent successfully. We will reply by email.';}catch{status.textContent='Email service needs activation. Please activate the FormSubmit email sent to info@lotusbio.cn, then try again.';}};document.querySelector('#quote-email').after(send);
 const copy=document.createElement('button');copy.type='button';copy.className='button';copy.textContent='Copy inquiry';copy.onclick=async()=>{try{await navigator.clipboard.writeText(message());document.querySelector('#quote-storage').textContent='Copied. Paste into an email to info@lotusbio.cn.';}catch{document.querySelector('#quote-storage').textContent='Please email info@lotusbio.cn manually.';}};send.after(copy);
 window.lotusQuoteMessage=message;
})();

